#!/bin/bash
# set -xv

 BASEDIR=${PWD}
 OPTION=${1}

 list_options="build provision destroy details"

 contains() { [[ ! -z "${2}" && "${1}" =~ (^|[[:space:]])${2}($|[[:space:]]) ]] && return 0  || return 1; }
 contains "${list_options}" "${1}"  || { printf "specify an option\n[${list_options}]\n\n"; exit 1; }

 case ${OPTION} in
       build)  pushd ./provisioning/aws;
               ansible-playbook         -vvvv create_proxy.yaml;   
               popd;
               ;;
   provision)  pushd ./provisioning/aws;
               ansible-playbook -vvvv playbook_docker_prereqs.yml
               ansible-playbook -vvvv playbook_test.yml -e "PLATFORM=aws";
	       popd;
               ;;
     destroy)  pushd ./provisioning/aws;
               ansible-playbook destroy_proxy.yaml     -vvvv      -e "ENVIRONMENT=${PROXY_ENV}";
               popd;
               ;;
     details)  ;;
           *)  echo "run_proxy [${list_options}]";
               ;;
 esac
