---

 - name: Gather EC2 Server Facts
   ec2_instance_info:
     region: "{{ec2_region}}"
     filters:
       instance-state-name: running
       "tag:Type": "{{GROUP_NAME}}"
   register: ec2

 - name: Delete "{{group_name}}" servers from known_hosts "{{item.public_ip_address}}"
   with_items: "{{ec2.instances}}"
   known_hosts:
     name: "{{item.public_ip_address}}"
     state: absent
   loop_control:
     label: "{{item.tags.Name}}"

 - name: Delete "{{group_name}}" servers from known_hosts "{{item.private_ip_address}}"
   with_items: "{{ec2.instances}}"
   known_hosts:
     name: "{{item.private_ip_address}}"
     state: absent
   loop_control:
     label: "{{item.tags.Name}}"

 - name: Delete "{{group_name}}" servers from known_hosts "{{item.private_dns_name}}"
   with_items: "{{ec2.instances}}"
   known_hosts:
     name: "{{item.private_dns_name}}"
     state: absent
   loop_control:
     label: "{{item.tags.Name}}"

 - name: Delete "{{group_name}}" servers from known_hosts "{{item.tags.Name}}"
   with_items: "{{ec2.instances}}"
   known_hosts:
     name: "{{item.tags.Name}}"
     state: absent
   loop_control:
     label: "{{item.tags.Name}}"

...

